// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB_BO_vdVgtlARd2tlg2VvjnAUvWHpMKFU',
//     appId: '1:507642215529:web:301a3217bde4fbe08bf6f8',
//     messagingSenderId: '507642215529',
//     projectId: 'my-flutter-fire-hn',
//     authDomain: 'my-flutter-fire-hn.firebaseapp.com',
//     storageBucket: 'my-flutter-fire-hn.appspot.com',
//     measurementId: 'G-NK1H597MZC',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAmlJKmZxK4UN0OD65aKST59u-FlZWursE',
//     appId: '1:507642215529:android:f043b19bd2c93ffb8bf6f8',
//     messagingSenderId: '507642215529',
//     projectId: 'my-flutter-fire-hn',
//     storageBucket: 'my-flutter-fire-hn.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBrsxrd58g4MmhOOA_7smUSQAHMkfhUZ4g',
//     appId: '1:507642215529:ios:1a24da062db68b658bf6f8',
//     messagingSenderId: '507642215529',
//     projectId: 'my-flutter-fire-hn',
//     storageBucket: 'my-flutter-fire-hn.appspot.com',
//     iosBundleId: 'com.example.hackerNews',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBrsxrd58g4MmhOOA_7smUSQAHMkfhUZ4g',
//     appId: '1:507642215529:ios:b009f88a6d22fbc28bf6f8',
//     messagingSenderId: '507642215529',
//     projectId: 'my-flutter-fire-hn',
//     storageBucket: 'my-flutter-fire-hn.appspot.com',
//     iosBundleId: 'com.example.hackerNews.RunnerTests',
//   );
// }
